export const FROM_BACK_TO_POPUP = 'FROM_BACK_TO_POPUP';
export const CLOSE_WINDOW = 'CLOSE_WINDOW';
export const GET_WALLET_SERVICE_STATE = 'GET_WALLET_SERVICE_STATE';
export const APP_CONNECT = 'APP_CONNECT';
export const GET_TAB_ID_INNER_EVENT_REQUEST = 'GET_TAB_ID_INNER_EVENT_REQUEST';
export const POPUP_CLOSED = 'POPUP_CLOSED';

export const RESPONSE_TYPE = 'RESPONSE_TYPE';
export const REQUEST_TYPE = 'REQUEST_TYPE';

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const FORGET_IDENTITY_REQUEST = 'FORGET_IDENTITY_REQUEST';
export const SIGN_REQUEST = 'SIGN_REQUEST';
export const INSCRIBE_REQUEST = 'INSCRIBE_REQUEST';
export const MESSAGE_SIGN_REQUEST = 'MESSAGE_SIGN_REQUEST';
export const BROADCAST_REQUEST = 'BROADCAST_REQUEST';
export const GET_BALANCE_REQUEST = 'GET_BALANCE_REQUEST';
export const GET_INSCRIPTIONS_REQUEST = 'GET_INSCRIPTIONS_REQUEST';
export const GET_UTXOS_REQUEST = 'GET_UTXOS_REQUEST';

export const GET_ACCOUNT_REQUEST_RESPONSE = 'GET_ACCOUNT_REQUEST_RESPONSE';
export const FORGET_IDENTITY_REQUEST_RESPONSE =
  'FORGET_IDENTITY_REQUEST_RESPONSE';
export const SIGN_REQUEST_RESPONSE = 'SIGN_REQUEST_RESPONSE';
export const INSCRIBE_REQUEST_RESPONSE = 'INSCRIBE_REQUEST_RESPONSE';
export const MESSAGE_SIGN_REQUEST_RESPONSE = 'MESSAGE_SIGN_REQUEST_RESPONSE';
export const BROADCAST_REQUEST_RESPONSE = 'BROADCAST_REQUEST_RESPONSE';
export const GET_BALANCE_REQUEST_RESPONSE = 'GET_BALANCE_REQUEST_RESPONSE';
export const GET_INSCRIPTIONS_REQUEST_RESPONSE =
  'GET_INSCRIPTIONS_REQUEST_RESPONSE';
export const GET_UTXOS_REQUEST_RESPONSE = 'GET_UTXOS_REQUEST_RESPONSE';

export const GET_ACCOUNT_SUCCESS_RESPONSE = 'GET_ACCOUNT_SUCCESS_RESPONSE';
export const GET_ACCOUNT_REJECT_RESPONSE = 'GET_ACCOUNT_REJECT_RESPONSE';

export const INSCRIBE_SUCCESS_RESPONSE = 'INSCRIBE_SUCCESS_RESPONSE';
export const INSCRIBE_REJECT_RESPONSE = 'INSCRIBE_REJECT_RESPONSE';

export const SIGN_SUCCESS_RESPONSE = 'SIGN_SUCCESS_RESPONSE';
export const SIGN_REJECT_RESPONSE = 'SIGN_REJECT_RESPONSE';

export const MESSAGE_SIGN_SUCCESS_RESPONSE = 'MESSAGE_SIGN_SUCCESS_RESPONSE';
export const MESSAGE_SIGN_REJECT_RESPONSE = 'MESSAGE_SIGN_REJECT_RESPONSE';

export const FORGET_IDENTITY_SUCCESS_RESPONSE =
  'FORGET_IDENTITY_SUCCESS_RESPONSE';
export const FORGET_IDENTITY_REJECT_RESPONSE =
  'FORGET_IDENTITY_REJECT_RESPONSE';

export const BROADCAST_SUCCESS_RESPONSE = 'BROADCAST_SUCCESS_RESPONSE';
export const BROADCAST_REJECT_RESPONSE = 'BROADCAST_REJECT_RESPONSE';

export const GET_BALANCE_SUCCESS_RESPONSE = 'GET_BALANCE_SUCCESS_RESPONSE';
export const GET_BALANCE_REJECT_RESPONSE = 'GET_BALANCE_REJECT_RESPONSE';

export const GET_INSCRIPTIONS_SUCCESS_RESPONSE =
  'GET_INSCRIPTIONS_SUCCESS_RESPONSE';
export const GET_INSCRIPTIONS_REJECT_RESPONSE =
  'GET_INSCRIPTIONS_REJECT_RESPONSE';

export const GET_UTXOS_SUCCESS_RESPONSE = 'GET_UTXOS_SUCCESS_RESPONSE';
export const GET_UTXOS_REJECT_RESPONSE = 'GET_UTXOS_REJECT_RESPONSE';

export const SIGN_PSBT_CONNECT = 'SIGN_PSBT_CONNECT';
export const MESSAGE_SIGN_CONNECT = 'MESSAGE_SIGN_CONNECT';
export const FORGET_IDENTITY_CONNECT = 'FORGET_IDENTITY_CONNECT';
export const GET_ACCOUNT_CONNECT = 'GET_ACCOUNT_CONNECT';
export const BROADCAST_CONNECT = 'BROADCAST_CONNECT';
export const GET_BALANCE_CONNECT = 'GET_BALANCE_CONNECT';
export const GET_INSCRIPTIONS_CONNECT = 'GET_INSCRIPTIONS_CONNECT';
export const GET_UTXOS_CONNECT = 'GET_UTXOS_CONNECT';
export const INSCRIBE_CONNECT = 'INSCRIBE_CONNECT';

export const SERVICE_EVENT_REQUEST = 'SERVICE_EVENT_REQUEST';
export const SERVICE_EVENT_RESPONSE = 'SERVICE_EVENT_RESPONSE';

export const LOGIN_REJECT = 'LOGIN_REJECT';
export const SIGN_REJECT = 'SIGN_REJECT';
export const INSCRIBE_REJECT = 'INSCRIBE_REJECT';
export const BROADCAST_REJECT = 'BROADCAST_REJECT';
export const MESSAGE_SIGN_REJECT = 'MESSAGE_SIGN_REJECT';
export const BALANCE_REJECT = 'BALANCE_REJECT';
export const INSCRIPTIONS_REJECT = 'INSCRIPTIONS_REJECT';
export const UTXOS_REJECT = 'UTXOS_REJECT';

export const INVALID_PARAMS = 'INVALID_PARAMS';
export const INVALID_ADDRESS = 'INVALID_ADDRESS';

export const SEND_BITCOIN_REQUEST = 'SEND_BITCOIN_REQUEST';
export const SEND_BITCOIN_SUCCESS_RESPONSE = 'SEND_BITCOIN_SUCCESS_RESPONSE';
export const SEND_BITCOIN_REJECT_RESPONSE = 'SEND_BITCOIN_REJECT_RESPONSE';
export const SEND_BITCOIN_REQUEST_RESPONSE = 'SEND_BITCOIN_REQUEST_RESPONSE';

export const SEND_INSCRIPTION_REQUEST = 'SEND_INSCRIPTION_REQUEST';
export const SEND_INSCRIPTION_SUCCESS_RESPONSE =
  'SEND_INSCRIPTION_SUCCESS_RESPONSE';
export const SEND_INSCRIPTION_REJECT_RESPONSE =
  'SEND_INSCRIPTION_REJECT_RESPONSE';
export const SEND_INSCRIPTION_REQUEST_RESPONSE =
  'SEND_INSCRIPTION_REQUEST_RESPONSE';

export const SEND_BITCOIN_REJECT = 'SEND_BITCOIN_REJECT';
export const SEND_INSCRIPTION_REJECT = 'SEND_INSCRIPTION_REJECT';
